theme: jekyll-theme-slate
title: Utilizing Medicare reports to reveal how full hospitals have been
description: Only hard-to-find sources will show a comprehensive picture of hospital capacity, critical during the early days of COVID-19.
